repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: src/problems/data
      - id: trailing-whitespace
      - id: check-toml
      - id: check-added-large-files
        args: [ --maxkb=1024 ]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: fmt
      - id: clippy
