[package]
name    = "projecteuler-rust"
version = "0.0.1"
authors = [ "mlefebvre" ]
edition = "2021"

[dependencies]
rand = "0.8"
num = "0.4"
phf = { version = "0.10", features = ["macros"] }
itertools = "0.10"
factorial = "0.2"
bitvec = "1"
